# Generated by Django 4.0.3 on 2022-04-09 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('image1', models.ImageField(upload_to='pics/')),
                ('image2', models.ImageField(upload_to='pics/')),
                ('image3', models.ImageField(upload_to='pics/')),
                ('image4', models.ImageField(upload_to='pics/')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('rent', models.FloatField()),
                ('location', models.CharField(max_length=300)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pics/')),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('token', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.renthome')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usersdata')),
            ],
        ),
        migrations.AddField(
            model_name='renthome',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usersdata'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.renthome')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usersdata')),
            ],
        ),
    ]
