# Generated by Django 4.0.3 on 2022-04-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contract_renthome_transactions_usersdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
