# Generated by Django 4.0.3 on 2022-04-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contract_renthome_transactions_usersdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.renthome')),
            ],
        ),
    ]
