# Generated by Django 4.0.3 on 2022-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_renthome_rent_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthome',
            name='description',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
