# Generated by Django 4.0.3 on 2022-04-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_renthome_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthome',
            name='pincode',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
