# Generated by Django 4.0.3 on 2022-04-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_renthome_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthome',
            name='location',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
