# Generated by Django 4.0.3 on 2022-04-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contract_duration'),
        ('base', '0006_alter_renthome_location'),
    ]

    operations = [
    ]
